replicaCount: 1

image:
  repository: grafana/loki
  pullPolicy: IfNotPresent
  tag: "2.4.1"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: LoadBalancer
  port: 3100

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: loki.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: 
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /live
    port: 3100

readinessProbe:
  httpGet:
    path: /ready
    port: 3100

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

lokiConfig:
  storage_config:
    boltdb_shipper:
      active_index_directory: /data/loki/index
      cache_location: /data/loki/cache
      shared_store: s3
    filesystem:
      directory: /data/loki/chunks

  s3:
    bucket_name: <your-s3-bucket-name>
    endpoint: <your-s3-endpoint>
    access_key_id: <your-access-key-id>
    secret_access_key: <your-secret-access-key>
    insecure: false
    region: <your-s3-region>
